// Nhập kiểu Metadata từ Next.js để thiết lập siêu dữ liệu trang
import type { Metadata } from "next";
// Nhập các họ phông tùy chỉnh (Geist và Geist Mono) từ Google Fonts
import { Geist, Geist_Mono } from "next/font/google";
// Nhập kiểu CSS toàn cục
import "./globals.css";

// Cấu hình họ phông Geist Sans
// Gán nó cho biến CSS --font-geist-sans và tải tập hợp Latin
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Cấu hình họ phông Geist Mono cho văn bản không tỷ lệ
// Gán nó cho biến CSS --font-geist-mono và tải tập hợp Latin
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Xuất đối tượng siêu dữ liệu để thiết lập tiêu đề và mô tả trang mặc định
// Nó xuất hiện trong các thẻ trình duyệt và kết quả công cụ tìm kiếm
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Thành phần bố cục gốc bao bọc tất cả các trang trong ứng dụng
// Điều này đảm bảo bố cục, phông chữ và kiểu dáng nhất quán trong tất cả các tuyến đường
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // Props con an toàn về kiểu
}>) {
  return (
    <html lang="en"> {/* Đặt thuộc tính ngôn ngữ HTML thành Tiếng Anh */}
      <body
        // Áp dụng cả hai biến phông chữ và khử răng cưa để hiển thị văn bản mượt mà
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Hiển thị các thành phần/trang con tại đây */}
        {children}
      </body>
    </html>
  );
}
